<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CajeroDAL">
      <HintPath>..\..\..\..\..\..\Descargas\imagenes\Optativa\Proyecto\la-plantilla-del-banco\CajeroDAL\CajeroDAL\CajeroDAL\bin\Debug\net8.0\CajeroDAL.dll</HintPath>
    </Reference>
    <Reference Include="MySql.Data">
      <HintPath>C:\Users\Administrator\.nuget\packages\mysql.data\9.3.0\lib\net8.0\MySql.Data.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
